name: C++ CI Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup C++ environment
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure project
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpp-build
        path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: cpp-build

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tagname: Stickler-Protocol-${{ github.runnumber }}
        releasename: "Stickler Protocol Build ${{ github.runnumber }}"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        uploadurl: ${{ steps.createrelease.outputs.upload_url }}
        asset_path: ./cpp-build
        assetname: stickler-build-${{ github.runnumber }}.zip
        assetcontenttype: application/zip
